-- Migración: crear tabla notificaciones
-- Ejecutar en el SQL Editor de Supabase.
--
-- La tabla es genérica: sirve para cualquier tipo de notificación
-- (reseñas, mensajes, sistema, etc.). El campo `tipo` distingue el origen
-- y `payload` guarda datos adicionales opcionales en JSON.

CREATE TABLE IF NOT EXISTS public.notificaciones (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario    VARCHAR(50)  NOT NULL,          -- DNI del destinatario
    tipo          VARCHAR(50)  NOT NULL,          -- 'resena', 'mensaje', 'sistema', ...
    titulo        VARCHAR(200) NOT NULL,
    subtitulo     VARCHAR(500),
    vinculo       VARCHAR(500),                   -- URL relativa a la que navega al tocar
    leida         BOOLEAN      NOT NULL DEFAULT FALSE,
    payload       JSONB,                          -- datos extra opcionales
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Índice para consultas por usuario (la query más frecuente)
CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario
    ON public.notificaciones (id_usuario, leida, created_at DESC);

-- FK blanda: no forzamos integridad referencial con usuarios
-- para no bloquear inserciones si el usuario fue borrado.
